# Generated by Django 6.0 on 2025-12-30 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('product_moderate', 'Модерация товара'), ('product_deleted', 'Удаление товара'), ('status_changed', 'Изменение статуса'), ('new_order', 'Новый заказ'), ('new_review', 'Новый отзыв'), ('new_product', 'Новый товар'), ('new_seller_request', 'Заявка нового продавца'), ('new_promotion_request', 'Новая заявка на акцию')], max_length=30, verbose_name='Тип уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('endpoint', models.TextField(verbose_name='Endpoint')),
                ('p256dh', models.TextField(verbose_name='P256DH ключ')),
                ('auth', models.TextField(verbose_name='Auth ключ')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Браузер')),
                ('device', models.CharField(blank=True, max_length=100, null=True, verbose_name='Устройство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Push-подписка',
                'verbose_name_plural': 'Push-подписки',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
