# Generated by Django 6.0 on 2026-01-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sellers', '0003_sellerbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Пополнение (Продажа)'), ('withdrawal', 'Вывод средств'), ('hold', 'Заморозка (Hold)'), ('release', 'Разморозка (Списание с hold)'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип транзакции')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время транзакции')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма вывода')),
                ('status', models.CharField(choices=[('requested', 'Запрошен'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('completed', 'Выполнен'), ('failed', 'Неудача')], default='requested', max_length=20, verbose_name='Статус вывода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Запрос на вывод средств',
                'verbose_name_plural': 'Запросы на вывод средств',
                'ordering': ['-created_at'],
            },
        ),
    ]
