# Generated by Django 6.0 on 2026-01-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('discount', models.CharField(help_text='Скидка в формате MIN-MAX или конкретное число', max_length=10)),
                ('thumbnail', models.ImageField(help_text='Изображение для баннера', upload_to='promotions/')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Дата истечения акции', null=True)),
                ('is_expired', models.BooleanField(default=False, help_text='Истекла ли акция')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активна'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
            },
        ),
    ]
