# Generated by Django 6.0 on 2026-01-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован')], default='active', max_length=10, verbose_name='Статус')),
                ('store_name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('store_logo', models.FileField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Логотип магазина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='SellerInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
