# Generated by Django 6.0 on 2026-01-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBalance',
            fields=[
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to='sellers.seller', verbose_name='Продавец')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доступный баланс')),
                ('hold_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Удерживаемый баланс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Баланс продавца',
                'verbose_name_plural': 'Балансы продавцов',
            },
        ),
    ]
