# Generated by Django 6.0 on 2025-12-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
    ]
