# Generated by Django 6.0 on 2025-12-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('status', models.CharField(choices=[('delivered', 'Доставлен'), ('processing', 'В обработке'), ('shipped', 'В Пути'), ('cancelled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата доставки')),
                ('orders', models.ManyToManyField(related_name='groups', to='orders.order', verbose_name='Заказы в группе')),
            ],
            options={
                'verbose_name': 'Группа заказов',
                'verbose_name_plural': 'Группы заказов',
                'ordering': ['-created_at'],
            },
        ),
    ]
