# Generated by Django 6.0 on 2026-01-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('status', models.CharField(choices=[('delivered', 'Доставлен'), ('processing', 'В обработке'), ('shipped', 'В Пути'), ('seller_cancelled', 'Отменен продавцом'), ('buyer_cancelled', 'Отменен покупателем')], default='processing', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата доставки')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('payment_status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('failed', 'Неудача')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод оплаты')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакции')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
                'ordering': ['-created_at'],
            },
        ),
    ]
