# Generated by Django 6.0 on 2026-01-15 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_initial'),
        ('sellers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('status', models.CharField(choices=[('pending', 'Ожидание платежа'), ('processing', 'В обработке'), ('payment_failed', 'Ошибка платежа'), ('partially_completed', 'Частично завершен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=25, verbose_name='Общий статус заказа')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод оплаты')),
                ('payment_gateway_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID транзакции в шлюзе')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Основной заказ',
                'verbose_name_plural': 'Основные заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('return_requested', 'Запрошен возврат'), ('returned', 'Возвращен')], default='processing', max_length=20, verbose_name='Статус под-заказа')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма для продавца')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order', verbose_name='Основной заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Продукт')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_orders', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Элемент заказа (по продавцу)',
                'verbose_name_plural': 'Элементы заказа (по продавцам)',
                'ordering': ['-created_at'],
            },
        ),
    ]
