# Generated by Django 6.0 on 2026-01-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Доставлен'), ('processing', 'В обработке'), ('shipped', 'В Пути'), ('cancelled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
