# Generated by Django 6.0 on 2026-01-05 19:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=610, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Скидка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-ссылка')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('moderation_type', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=255, verbose_name='Тип модерации')),
                ('items_in_package', models.IntegerField(blank=True, null=True, verbose_name='Количество продуктов')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('expiration_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок годности')),
                ('equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комплектация')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('image', models.FileField(upload_to='products/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Рейтинг должен быть не менее 1'), django.core.validators.MaxValueValidator(5, 'Рейтинг должен быть не более 5')], verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('seller_response', models.TextField(blank=True, null=True, verbose_name='Ответ продавца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('image', models.FileField(upload_to='reviews/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение отзыва',
                'verbose_name_plural': 'Изображения отзывов',
                'ordering': ['-created_at'],
            },
        ),
    ]
