# Generated by Django 6.0 on 2026-01-01 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Рейтинг должен быть не менее 1'), django.core.validators.MaxValueValidator(5, 'Рейтинг должен быть не более 5')], verbose_name='Оценка'),
        ),
    ]
