# Generated by Django 6.0 on 2025-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
